open-telemetry/opamp-spec

- README.md
The README.md file is originally Apache 2.0-Licensed. It is an exact copy of
https://github.com/signalfx/opamp-spec/blob/main/README.md.
According to Apache License 2.0 requirements and OpenTelemetry guidelines
(https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md) we
are going to retain the original copyright notice.
As recommended by the guidelines we will add "Copyright The OpenTelemetry Authors"
notice once we make any changes to this file.
> Add initial copy of OpAMP spec

- README.md
See comment here https://docs.google.com/document/d/1auDpvnhnWGGUlXA5y2tNXt_NVwOlgTi7aLpKm9kvFPM/edit?disco=AAAAQbtH88o
We may want to add a different error message from Agent to Server so
it is useful to make this name specific to Server.
> Rename ErrorResponse to ServerErrorResponse

- README.md
This is an information field to help with troubleshooting.
Suggested here: https://docs.google.com/document/d/1auDpvnhnWGGUlXA5y2tNXt_NVwOlgTi7aLpKm9kvFPM/edit?disco=AAAAQu51GQY
> Add server_offered_version to AgentInstallStatus

- README.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/19
This clarifies that the hash of the effective config is calculated by the Agent.
> Clarify generation of EffectiveConfig hash

- README.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/5
This simplifies the protocol a bit and does not prevent the Agents to
have addons or packages that are actually composed of multiple files (which
can be stored in e.g. a zip or tar downdloadable file).
> Change addons and agent packages to only contain one downloadable file

- README.md
The explanation was missing in the spec and it is important
to have recommendations about what exactly should go in the
attributes.
> Add explanation of agent_attributes field

- README.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/7
Resolves https://github.com/open-telemetry/opamp-spec/issues/25
This change clarifies how the protocols should work when a particular
capability is not supported. It also defines how future extensions
for the protocol capabilities will work.
> Add ability to indicate Capabilities in the protocol

- README.md
Contributes to https://github.com/open-telemetry/opamp-spec/issues/28
> Clarify Connection Establishment and Restoring

- README.md
Following [the discussion](https://github.com/open-telemetry/opamp-spec/issues/26#issuecomment-973135214) this specifies that both HTTP 503 and HTTP 429 status codes could be used for throttling requests to server
Contributes to https://github.com/open-telemetry/opamp-spec/issues/26
> Support both HTTP 503 and 429 for throttling

- README.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/39
The DataForAgent message is unnecessary. Moved all fields from DataForAgent
to ServertoAgent and deleted DataForAgent.
> Eliminate DataForAgent message

- README.md
This eliminates oneof Body from AgentToServer and puts all fields in AgentToServer
which allows to include multiple messages in one AgentToServer. This can reduce
the number of roundtrips and makes it uniform with ServerToAgent.
Resolves https://github.com/open-telemetry/opamp-spec/issues/43
> Eliminate oneof Body from AgentToServer

- README.md
This field already exists in AgentAddonStatuses and is not needed
in StatusReport.
> Delete duplicate server_provided_all_addons_hash field

- README.md
Contributes to https://github.com/open-telemetry/opamp-spec/issues/31
The Addon version is added to the Server offers and to the Agent Status reports.
This covers the use case described in the issue:
"Agent downloads a different addon hash/version, the addon errors, the agent is
able to use the previous addon hash/version".
This may or may not cover the second use case:
"Agent uses multiple addon hashes/versions concurrently, using capabilities that
may have been removed and added across addon hashes/version".
The protocol does not allow reporting status of multiple versions concurrently,
but the Agent can still keep multiple versions around. It is not completely
clear from the description of the use case if this is sufficient.
> Add version field to Addons

- README.md
The field description is in the spec but the field is missing in the message.
The field somehow was lost during editing.
> Add capabilities field to ServerToAgent

- README.md
When implementing https://github.com/open-telemetry/opamp-go/pull/31
I found the Unspecified enum names clash. This fixes it.
> Fix capabilities enum name and value

- specification.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/65
- Added signature field to DownloadableFile message.
- Added a short explanation about how the signature field can be used
for detached signatures.
> Add support for detached signatures

- specification.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/67
Without specifying the hashing method it was useless for the purposes it claims to exist for
>The hash of the file content. Can be used by the Agent to verify that the file was downloaded correctly.
You can't verify that the hash matches the content if you don't know the hashing method.
Now it is precisely defined to be SHA256 of the content.
> Define that DownloadFile content hash method is SHA256

- specification.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/50
Certain applications may not need the OpAMP's capabilities enabled by WebSocket (ability to push configs from server without Agent's polling) and may prefer to implement a simpler HTTP transport. This is likely the case for short-lived Agents such as for example the ones running in AWS lambda. The HTTP transport is likely simpler to implement on the Server (easier to manage connections) and also removes an additional dependency (a WebSocket library) from the client.
We are also considering implementing OpAMP in OpenTelemetry SDKs, which can result in significantly larger number of OpAMP Agents connecting to the Server, so the Server has to handle a larger number of persistent WebSocket connections, which may pose more burden …
> Add plain HTTP transport to OpAMP

- .github/workflows/checks.yaml
The action is not properly triggered on PRs, e.g. https://github.com/open-telemetry/opamp-spec/pull/77
I am not completely sure why, but I copied the "on" trigger from the https://github.com/open-telemetry/opentelemetry-specification
repo where the action works fine, so hopefully this should fix it.
> Fix markdown-toc-check github action

- specification.md
Addons and agent packages were previously defined separately
in the spec but had a lot of similarities. This change combines
them into one concept of "packages". The resulting spec is
significantly shorter while providing the same functionality.
It may also reduce the code duplication in implementations.
Resolves https://github.com/open-telemetry/opamp-spec/issues/4
> Unify addons and agent packages

- specification.md
This changes splits connection settings by the type of the connection so that
each type has a corresponding message that records the appropriate data.
See proposal here https://github.com/open-telemetry/opamp-spec/issues/80#issuecomment-1125193943
I also deleted proxy-related settings since it wasn't clear when and how when
can be used. These can be added later when the use case is clear.
Contributes to https://github.com/open-telemetry/opamp-spec/issues/80
> Split connection settings by types

- specification.md
It's helpful to have a TOC, but there's a fair amount of scrolling to
do before you get to the text. If we enclose it in a details element,
the reader can show the TOC only when then need it.
Signed-off-by: James Peach <jpeach@cloudflare.com>
> Enclose the TOC in a details element.

- specification.md
Plain HTTP transport that uses polling is now part of the spec.
This sentence is no longer necessary.
> Delete reference to plain HTTP transport as if it does not exists

- specification.md
This is consistent with how [we do it for OTLP](https://github.com/open-telemetry/opentelemetry-proto/blob/main/README.md#maturity-level) and how OpenTelemetry [specifies maturity levels](https://github.com/open-telemetry/community/blob/47813530864b9fe5a5146f466a58bd2bb94edc72/maturity-matrix.yaml#L57).
> Use "Alpha" to denote the stability

- specification.md
The "Beta" definition is the same as for OTLP and links to
https://github.com/open-telemetry/community/blob/47813530864b9fe5a5146f466a58bd2bb94edc72/maturity-matrix.yaml#L57
> Declare OpAMP Beta

- specification.md
Github already shows contributors. At Otel we don't typically include
authors and contributors in the document text itself.
> Remove unnecessary attributions

- README.md
Link to BindPlane OP and the observIQ Distro
> Add Libraries, Platforms, and Agents sections to the Implementations

- README.md
Dear community, due to a transition into another role at a different organisation I am no longer able to allocate time to be an approver of OpAMP
Thank you all, it was a great pleasure to work with you and also a great opportunity to learn
> Remove pmm-sumo from approvers list

- specification.md
When health reporting was added we forgot to add a corresponding
bit in the AgentCapabilities. This adds the missing bit.
> Add missing ReportsHealth capability

- specification.md
Add ReportsRemoteConfig capability
Resolves https://github.com/open-telemetry/opamp-spec/issues/112
All other status fields have a corresponding capability bit except this
one. This results in a non-consistent looking implementation that
has to rely on AcceptsRemoteConfig bit instead to figure out if
RemoteConfigStatus reporting is expected, for example:
https://github.com/open-telemetry/opamp-go/pull/105/files#diff-620a7a2b42e4a4c60a590b0cca50053006e4555c6e70f38dece2f3a6d7ed1338R214
Adding this bit makes the status fields and their corresponding
capabilities bits consistent.
> Add ReportsRemoteConfig capability

- specification.md
Contributes to https://github.com/open-telemetry/opamp-spec/issues/114
> Clarify what is Agent, especially when Supervisor is used

- specification.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/121
In some languages enum fields are strongly typed and it is impossible to assigned OR-ed values to the enum field. This makes impossible to compose the bit fields properly.
This changes all bit field declarations from enum to uint64. The enum declarations stay, so that bit definitions are clear.
This must be a non-breaking change on the wire. The enum and uint64 are encoded exactly the same way on the wire.
> Change bitfields from enum to uint64

- .github/workflows/checks.yaml
- .gitignore
- Makefile
- proto/anyvalue.proto
- proto/opamp.proto
Contributes to https://github.com/open-telemetry/opamp-go/issues/133
Now that we are adding OpAMP Java implementation the protos can no longer live in opamp-go. We are moving the protos to the spec repo since it fits this repo's purpose naturally.
The proto files are copied verbatim from opamp-go. Any changes needed in the proto files can be done in a future PR.
In the future it is also worth exploring if we can delete the message definitions from specification.md and instead link them directly to the proto files so that we have a single source of truth.
> Move proto files to opamp-spec repo

- specification.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/123
We want stronger requirements to use compression.
> Change MAY to SHOULD for Server to Client compression

- specification.md
Contributes to https://github.com/open-telemetry/opamp-spec/issues/131
service.name is an existing OpenTelemetry convention. OpAMP is not in the business of defining OpenTelemetry's semantic conventions. I deleted the unnecessary wording that tried to add more meaning to the service.name that is not our business to do.
> Remove unnecessary recommendation about service.name

- specification.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/133
Thi is ane extensibility mechanism - a header for WebSocket messages. Every WebSocket message is composed of 2 parts: varint-encoded unsigned 64 bit integer header, followed by the serialized Protobuf AgentToServer/ServerToAgent messages.
The current value of the header is equal to 0. In the future when non-zero values of headers are introduced their use should be negotiated during the connection phase (via HTTP headers or via Capabilities fields). This is necessary to ensure interoperability between different OpAMP versions. Non-zero header values will not be a breaking change, they will only used after successful negotiation between the Client and Server.
Note: we don't need the header for plain HTTP transport. Any …
> Adding a header for WebSocket messages to allow future extensibility

- proto/opamp.proto
- specification.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/136
- Renamed `up` to `healthy`.
- `start_time_unix_nano` is no longer tied to `up` and is set independently.
> Clarify agent health reporting

- specification.md
The guarantees mostly mirror the guarantees for OTLP (https://github.com/open-telemetry/opentelemetry-proto/pull/432), the primary difference being that OpAMP has no gRPC services defined and does not need any guarantees for service definitions.
This PR reflects the OpAMP Workgroup's discussions.
Resolves https://github.com/open-telemetry/opamp-spec/issues/134
> Define OpAMP Protobuf schema stability guarantees

- specification.md
- Closes #148
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/2927
- Minor copyedits only to accompany some of the changes made per the task list below
Updates (task list taken from #148) made in this PR:
-> https://opentelemetry.io/docs/specs/otlp/
**Local repo preview**: https://github.com/open-telemetry/opamp-spec/blob/9ba5f927bec431e8997d0cdc6e406bd82740cd31/specification.md
/cc @tigrannajaryan @svrnm @cartermp
> [editorial] Spec updates for OTel website publication

- specification.md
The field was missing in specification.md, although it is correctly present in opamp.proto.
The filed is now added to specification.md.
Fixes https://github.com/open-telemetry/opamp-spec/issues/120
> Add missing "config_hash" field to AgentRemoteConfig

- specification.md
Usage of format requirement level implies somehow the recommendations are important part of the protocol. I think it is misleading. These are really recommendations, and certainly they are not complete or sufficient.
I think we should de-emphasize them a bit and really just keep as what they are: recommendations and warnings.
> Rewrite security recommendation to be non-normative

- specification.md
We have no immediate plans to add anything in this section. Removing for now. Can be added later.
> Remove "Performance and Scale" section

- specification.md
- Closes #157
- Adds the following link definition (take from the top of the spec file):
[beta]: https://github.com/open-telemetry/community/blob/47813530864b9fe5a5146f466a58bd2bb94edc72/maturity-matrix.yaml#L57
- Drops the period at the end of "Status: [Beta]" (there shouldn't be any)
- Makes a slight copyedit to a paragraph that refers to the `[Beta]` notation in the schema
**Preview**: https://github.com/open-telemetry/opamp-spec/blob/c9b76fd6592aca93ee7f2903487fdce5fd2eaef1/specification.md
> [editorial] Add missing [Beta] markdown link definition + copyedit

- proto/opamp.proto
- specification.md
- Followup to #158
- Fixes specification where a regular paragraph of text was prefixed with `//`, https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#servertoagentcommand-message:
> <img width="368" alt="image" src="https://github.com/open-telemetry/opamp-spec/assets/4140793/074ec329-b1cb-43fc-a6f6-75f2d1c9dd33">
- Applies the #158 fix across files, including `opamp.proto` -- at most comments are changed (I'm not sure if you still consider this an editorial change in such a case)
**Preview**:
- https://github.com/open-telemetry/opamp-spec/blob/c2402be375af766bf02fb9b275928da0b2f79a98/specification.md
- https://github.com/open-telemetry/opamp-spec/blob/c2402be375af766bf02fb9b275928da0b2f79a98/specification.md#servertoagentcommand-message
> [editorial] Drop period after "Status: [Beta]"

- specification.md
- Closes #150 now that the semconv pages are hosted on the OTel website
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/2721
/cc @jsuereth @joaopgrassi
> [editorial] Link to semconv OTel website page

- faq.md
- specification.md
The FAQ was very useful for initial phase of spec development but is now more of historical interest. Moving it to a separate file to avoid distracting spec readers.
> Move FAQ to a separate file

- proto/opamp.proto
- specification.md
Resolves https://github.com/open-telemetry/opamp-spec/issues/13
Uses [Development] label as the indication of the least mature level proposed in this upcoming OTEP:
https://github.com/open-telemetry/oteps/pull/232/
[UPDATE]: I added a draft implementation in Go to demonstrate how the CSR flow works: https://github.com/open-telemetry/opamp-go/pull/192
> Add client-initiated certificate request flow (CSR)

- proto/opamp.proto
- specification.md
As discussed in #165, this PR replaces the AgentHealth message with a wire-backwards-compatible ComponentHealth message. The ComponentHealth message allows reporting health for nested sub-components, component status, and status timestamp, while retaining the fields from the original AgentHealth message.
> Add ComponentHealth message

- specification.md
- Context: the original link resulted in too many redirects for the OTel website link checker
- Changes the FB PDF URL to be closer to home (resolves a few 3xx's)
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3615
/cc @svrnm
> [editorial] Fix fb link to PDF

- specification.md
- Fixes #169
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3804
- Drops the 404 link https://pwn.recipes/posts/roll-your-own-e2ee-protocol/. I [can't find a reference to this anywhere](https://www.google.com/search?q=roll+your+own+e2ee+protocol).
- Cleans up markdown syntax, simplifying the duplication of `[https://some-path](https://some-path)` by `<https://some-path>`
- Other copyedits
cc @theletterf @svrnm
> [editorial] Drop 404 link and cleanup references

- specification.md
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3804
- Switches to using canonical link to "ACME End User Client and Code Signing Certificates"
- Replaces raw URLs by proper markdown links so as to match other entries in the **References** section
> [editorial] Use canonical link to "ACME End User Client and Code Signing Certificates"

- README.md
My participation in this SIG has been quite limited for some time. Correspondingly, I believe it would be appropriate to move to emeritus status at this time.
> Move Dan Jaglowski to Emeritus Approver

- README.md
I've not had time or bandwidth to follow the work in this repo.
> move codeboten to emeritus approver

- .markdown_link_check_config.json
- specification.md
> Fix Markdown link checking action

- proto/opamp.proto
- specification.md
Fixes #161
This PR amends two field names in TLSCertificate message, making them more descriptive. I've opted to use the shorter `cert` term, to avoid confusion with the parent message which is used as `TLSCertificate certificate` in three places.
It's my first PR to the opamp-spec repo, so let me know if there's something I'm missing, I'd be happy to fix that.
> Amend field names in TLSCertificate message

- proto/opamp.proto
- specification.md
Fixes #194 
This PR amends the spec and protos to include an optional set of headers in DownloadableFile, to be used in the download GET request to set up auth parameters. 
This is only one of the ways we could implement setting authentication paramaters to be used by Agents when downloading packages, but it is consistent with other uses of the headers field and generic enough to cover different use cases so I feel it's worth considering.
> Allow setting Headers in DownloadableFile message

- proto/opamp.proto
- specification.md
This PR adds a new ComponentDetails type that allows agents to communicate metadata relating to the components available in the agent.
> Add message about available components to AgentDetails

- specification.md
A couple small bits of documentation were missed during https://github.com/open-telemetry/opamp-spec/pull/201. This PR adds that documentation.
> Add missed AvailableComponents documentation

- proto/opamp.proto
- specification.md
As suggested in the implementation PR (https://github.com/open-telemetry/opamp-go/pull/341), the download rate should be a double (float64 in go).
> Change PackageStatus.download_details.download_bytes_per_second to double

- specification.md
See proto/opamp.proto for the correct name.
> Fix typo headers -> Headers

- specification.md
Add descriptions for all attributes in the TLSConnectionSettings message and change the guidance for what to do if the message is not included with offered connection settings to be in-line with other offered settings.
> Add TLSConnectionSettings message attribute descriptions
